
CREATE TABLE TICKET (

    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE TEXT NOT NULL,
    CLIENT_ID INTEGER REFERENCES PERSON(ID) NOT NULL,
    STATUS TEXT NOT NULL = 'OPEN',
    MESSAGE TEXT NOT NULL,
    DEPARTMENT TEXT FOREIGN KEY,
    CREATED_AT DATETIME NOT NULL,

)

CREATE TABLE PERSON (

    UP INTEGER PRIMARY KEY,
    EMAIL TEXT NOT NULL,
    NAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    ROLE TEXT NOT NULL = 'Student',
    DEPARTMENT DEPARTMENT,

) 

CREATE TABLE DEPARTMENT (

    NAME TEXT PRIMARY KEY NOT NULL,

)

CREATE TABLE TICKET_MESSAGE (
    TEXT TEXT NOT NULL,
    TICKET_ID INTEGER REFERENCES TICKET(EMAIL) ON DELETE CASCADE ON UPDATE CASCADE,
    PERSON_ID INTEGER REFERENCES PERSON(EMAIL) ON DELETE CASCADE ON UPDATE CASCADE,
    CREATED_AT DATETIME NOT NULL,
    DOCUMENT_ID INTEGER REFERENCES DOCUMENT(EMAIL) ON DELETE CASCADE ON UPDATE CASCADE,
)

CREATE TABLE DOCUMENT (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    NAME TEXT NOT NULL,
    CONTENT BLOB NOT NULL,
    CREATED_AT DATETIME NOT NULL
)

CREATE TABLE TICKET_AGENTS(
    TICKET_ID INTEGER REFERENCES TICKET(ID) ON DELETE CASCADE ON UPDATE CASCADE,
    AGENT_ID INTEGER REFERENCES PERSON(EMAIL) ON DELETE CASCADE ON UPDATE CASCADE,
    PRIMARY KEY (TICKET_ID, AGENT_ID)
)
