
CREATE TABLE TICKET (

    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TITLE TEXT NOT NULL,
    AGENT_ID INTEGER REFERENCES PERSON(EMAIL) ON DELETE CASCADE ON UPDATE CASCADE, 
    CLIENT_ID INTEGER REFERENCES PERSON(ID) NOT NULL,
    STATUS TEXT NOT NULL = 'OPEN',
    MESSAGE TEXT NOT NULL,
    DEPARTMENT TEXT FOREIGN KEY,
    CREATED_AT DATETIME NOT NULL,

)

CREATE TABLE PERSON (

    EMAIL TEXT PRIMARY KEY NOT NULL,
    NAME TEXT NOT NULL,
    PASSWORD TEXT NOT NULL,
    ROLE TEXT NOT NULL = 'CLIENT',
    DEPARTMENT DEPARTMENT,

) 

CREATE TABLE DEPARTMENT (

    NAME TEXT PRIMARY KEY NOT NULL,

)
